#pragma once

// Sea of Thieves (1.1.6) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "SoT_BP_Anim_NPCBasePortSign_classes.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_HIKLookAt_13BFA1154D67C96FFE9838AB98FF2628
struct UBP_Anim_NPCBasePortSign_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_HIKLookAt_13BFA1154D67C96FFE9838AB98FF2628_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_TransitionResult_B7D7BFE443C78A4DB09BF2954F9FB2A7
struct UBP_Anim_NPCBasePortSign_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_TransitionResult_B7D7BFE443C78A4DB09BF2954F9FB2A7_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_TransitionResult_3F28B3CF423C1190623B60A13F607335
struct UBP_Anim_NPCBasePortSign_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_TransitionResult_3F28B3CF423C1190623B60A13F607335_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_TransitionResult_43F9A72248609D19E5705EA6BAB1F30C
struct UBP_Anim_NPCBasePortSign_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_TransitionResult_43F9A72248609D19E5705EA6BAB1F30C_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_TransitionResult_7C8989714AD1ACE3E3E052B27235B0BB
struct UBP_Anim_NPCBasePortSign_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_TransitionResult_7C8989714AD1ACE3E3E052B27235B0BB_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_TransitionResult_30C5D665441234F12947C383078A8A68
struct UBP_Anim_NPCBasePortSign_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_TransitionResult_30C5D665441234F12947C383078A8A68_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_TransitionResult_F745863A43BD24C6D469ADB62F2DCCEA
struct UBP_Anim_NPCBasePortSign_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_TransitionResult_F745863A43BD24C6D469ADB62F2DCCEA_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_SequencePlayer_E5638D18445051F1530FEE8B5A4F05EC
struct UBP_Anim_NPCBasePortSign_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_SequencePlayer_E5638D18445051F1530FEE8B5A4F05EC_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_SequencePlayer_BB97615A44B9DB9275800DB3B00CC81D
struct UBP_Anim_NPCBasePortSign_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_SequencePlayer_BB97615A44B9DB9275800DB3B00CC81D_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_TransitionResult_09CEE3C24178A5605CCF648191962615
struct UBP_Anim_NPCBasePortSign_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_TransitionResult_09CEE3C24178A5605CCF648191962615_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_TransitionResult_A291661E44C69BA0E4EF43964E4A6942
struct UBP_Anim_NPCBasePortSign_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_TransitionResult_A291661E44C69BA0E4EF43964E4A6942_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_SequencePlayer_7CE6B2C24E75C281815BC0864650981A
struct UBP_Anim_NPCBasePortSign_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_SequencePlayer_7CE6B2C24E75C281815BC0864650981A_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_SequencePlayer_69398C85415842511F29849928EE840C
struct UBP_Anim_NPCBasePortSign_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_SequencePlayer_69398C85415842511F29849928EE840C_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_TransitionResult_BC0AAFE64F928C6D83C3CD845DE4392F
struct UBP_Anim_NPCBasePortSign_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_TransitionResult_BC0AAFE64F928C6D83C3CD845DE4392F_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_TransitionResult_AEFCE8034CC275366AE4CDA1DE42244B
struct UBP_Anim_NPCBasePortSign_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_TransitionResult_AEFCE8034CC275366AE4CDA1DE42244B_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_SequencePlayer_6571DC784B043D27EED1E59873E2E9A8
struct UBP_Anim_NPCBasePortSign_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_SequencePlayer_6571DC784B043D27EED1E59873E2E9A8_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_BlendListByBool_E5490ABD4826025E17DA0E875C64C216
struct UBP_Anim_NPCBasePortSign_C_EvaluateGraphExposedInputs_ExecuteUbergraph_BP_Anim_NPCBasePortSign_AnimGraphNode_BlendListByBool_E5490ABD4826025E17DA0E875C64C216_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.BlueprintUpdateAnimation
struct UBP_Anim_NPCBasePortSign_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.AnimNotify_StartLookat
struct UBP_Anim_NPCBasePortSign_C_AnimNotify_StartLookat_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.AnimNotify_StopLookAt
struct UBP_Anim_NPCBasePortSign_C_AnimNotify_StopLookAt_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.AnimNotify_IdleVariantChange
struct UBP_Anim_NPCBasePortSign_C_AnimNotify_IdleVariantChange_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.AnimNotify_NPCItemAnimation
struct UBP_Anim_NPCBasePortSign_C_AnimNotify_NPCItemAnimation_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.AnimNotify_InactiveVariantChange
struct UBP_Anim_NPCBasePortSign_C_AnimNotify_InactiveVariantChange_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.AnimNotify_InteractVariantChange
struct UBP_Anim_NPCBasePortSign_C_AnimNotify_InteractVariantChange_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.AnimNotify_LH_UseItem_2
struct UBP_Anim_NPCBasePortSign_C_AnimNotify_LH_UseItem_2_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.AnimNotify_LH_UseItem_3
struct UBP_Anim_NPCBasePortSign_C_AnimNotify_LH_UseItem_3_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.AnimNotify_LH_UseItem_4
struct UBP_Anim_NPCBasePortSign_C_AnimNotify_LH_UseItem_4_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.AnimNotify_LH_UseItem_5
struct UBP_Anim_NPCBasePortSign_C_AnimNotify_LH_UseItem_5_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.AnimNotify_LH_DestroyItem
struct UBP_Anim_NPCBasePortSign_C_AnimNotify_LH_DestroyItem_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.AnimNotify_RH_UseItem_2
struct UBP_Anim_NPCBasePortSign_C_AnimNotify_RH_UseItem_2_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.AnimNotify_RH_UseItem_3
struct UBP_Anim_NPCBasePortSign_C_AnimNotify_RH_UseItem_3_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.AnimNotify_RH_UseItem_4
struct UBP_Anim_NPCBasePortSign_C_AnimNotify_RH_UseItem_4_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.AnimNotify_RH_UseItem_5
struct UBP_Anim_NPCBasePortSign_C_AnimNotify_RH_UseItem_5_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.AnimNotify_RH_DestroyItem
struct UBP_Anim_NPCBasePortSign_C_AnimNotify_RH_DestroyItem_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.AnimNotify_RH_DetachItem
struct UBP_Anim_NPCBasePortSign_C_AnimNotify_RH_DetachItem_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.AnimNotify_LH_DetachItem
struct UBP_Anim_NPCBasePortSign_C_AnimNotify_LH_DetachItem_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.AnimNotify_LH_AttachItem
struct UBP_Anim_NPCBasePortSign_C_AnimNotify_LH_AttachItem_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.AnimNotify_RH_AttachItem
struct UBP_Anim_NPCBasePortSign_C_AnimNotify_RH_AttachItem_Params
{
};

// Function BP_Anim_NPCBasePortSign.BP_Anim_NPCBasePortSign_C.ExecuteUbergraph_BP_Anim_NPCBasePortSign
struct UBP_Anim_NPCBasePortSign_C_ExecuteUbergraph_BP_Anim_NPCBasePortSign_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
